const plants=[
 {id:1,name:'Tomato · Roma',zone:'Bed A · Node 01',moisture:42,temp:23.4,light:780,need:38,health:'Healthy',note:'Moisture is in the ideal range. Strong light exposure today.'},
 {id:2,name:'Basil · Genovese',zone:'Bed A · Node 02',moisture:29,temp:22.8,light:640,need:40,health:'Attention',note:'Moisture is trending below target. Water within the next 2 hours.'},
 {id:3,name:'Lettuce · Butterhead',zone:'Bed B · Node 03',moisture:56,temp:21.1,light:910,need:45,health:'Healthy',note:'Conditions are stable. No action required.'}
];
const tasks=[['Water basil · Node 02','Due now',false],['Check greenhouse vents','Today',false],['Review weekly growth report','Tomorrow',false],['Harvest readiness check','Fri',false]];
let readAlerts=new Set(), activePage='dashboard';
const qs=s=>document.querySelector(s), qsa=s=>document.querySelectorAll(s);
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;qs('#toastContainer').appendChild(t);setTimeout(()=>t.remove(),2600)}
function nav(view){activePage=view;qsa('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));qsa('.view-page').forEach(p=>p.classList.remove('active-page'));qs('#page-'+view).classList.add('active-page');render(view)}
function header(kicker,title,sub){return `<div class="topbar"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${sub}</p></div><div class="date-chip">● Live · Tue 15 Sep 2026</div></div>`}
function lineChart(values){const pts=values.map((v,i)=>`${(i/(values.length-1))*100},${92-v*.72}`).join(' ');const area=`0,92 ${pts} 100,92`;return `<div class="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path class="chart-area" d="M ${area} Z"/><path class="chart-grid" d="M0 20H100M0 46H100M0 72H100M0 92H100"/><polyline class="chart-line" points="${pts}"/></svg></div><div class="chart-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div>`}
function dashboard(){
 const attention=plants.filter(p=>p.health==='Attention').length;
 return header('Aisha’s Garden · Overview','Good morning, Aisha.','Your farm is healthy — Xylem is watching for problems before they become crop loss.')+
 `<div class="grid stats">
  <div class="card stat"><div class="stat-head">Plant health <span class="stat-icon">♥</span></div><div class="stat-value">${attention? '89':'100'}%</div><div class="stat-foot ${attention?'warning':'good'}">${attention?'1 plant needs attention':'All plants within target'}</div></div>
  <div class="card stat"><div class="stat-head">Soil moisture <span class="stat-icon">◒</span></div><div class="stat-value">42%</div><div class="stat-foot">Live · 3 sensor nodes</div></div>
  <div class="card stat"><div class="stat-head">Light level <span class="stat-icon">☼</span></div><div class="stat-value">780 <small style="font-size:13px">lx</small></div><div class="stat-foot">+8% vs yesterday</div></div>
  <div class="card stat"><div class="stat-head">Next weather <span class="stat-icon">☁</span></div><div class="stat-value">24°</div><div class="stat-foot">Sunny · rain 10%</div></div>
 </div>
 <div class="grid main-grid">
  <div class="card section"><div class="section-head"><h2>Early alerts</h2><span>${attention+2} notifications</span></div>
   <div class="alert"><div class="alert-icon">!</div><div style="flex:1"><h3>Basil is getting thirsty</h3><p>Node 02 reports 29% soil moisture — below its 40% target. Watering now should prevent stress.</p></div><button class="btn btn-primary" id="waterAlert">Water now</button></div>
   <div class="alert" style="background:#f3f7f8;border-color:#dce7e9"><div class="alert-icon" style="background:#dfeef0;color:#3d7480">☁</div><div><h3>Rain expected Thursday</h3><p>10–15 mm forecast. Xylem recommends delaying the next irrigation cycle.</p></div></div>
   <div class="section-head" style="margin-top:19px"><h2>Live plant health</h2><span>Updates every few seconds</span></div>
   <div class="plant-list">${plants.map(p=>`<div class="plant-row"><div><div class="plant-name">${p.name}</div><div class="plant-zone">${p.zone}</div></div><div><div class="meter ${p.health==='Attention'?'low':''}"><i style="width:${p.moisture}%"></i></div></div><div class="metric">${p.moisture}%<small>moisture</small></div><div><span class="health ${p.health==='Attention'?'attention':''}">${p.health}</span></div></div>`).join('')}</div>
  </div>
  <div class="card section"><div class="section-head"><h2>Weather outlook</h2><span>BOM · next 3 days</span></div><div class="weather"><div class="weather-day"><div class="weather-icon">☀</div><div><strong>Today</strong><small>Clear · low wind</small></div><div class="temp">24° / 15°</div></div><div class="weather-day"><div class="weather-icon">⛅</div><div><strong>Wed 16</strong><small>Partly cloudy</small></div><div class="temp">23° / 16°</div></div><div class="weather-day"><div class="weather-icon">🌧</div><div><strong>Thu 17</strong><small>Rain · 80%</small></div><div class="temp">21° / 17°</div></div></div><div class="ai-card" style="margin-top:18px"><div class="ai-label">✦ Xylem intelligence</div><h2>Water basil before 2 PM.</h2><p>Its moisture has fallen 11% over the last 24 hours. Forecast rain is not expected until Thursday.</p></div></div>
 </div>
 <div class="grid bottom-grid">
  <div class="card section"><div class="section-head"><h2>Soil moisture · 7 days</h2><span>Target 40–70%</span></div>${lineChart([61,57,53,49,45,38,42])}</div>
  <div class="card section"><div class="section-head"><h2>Today’s checklist</h2><span>2 / 4 complete</span></div><div class="checklist">${tasks.map((t,i)=>`<div class="task ${t[2]?'done':''}" data-task="${i}"><button class="check">${t[2]?'✓':''}</button><span>${t[0]}</span><small>${t[1]}</small></div>`).join('')}</div></div>
 </div>`;
}
function plantsView(){return header('Your growing system','My plants','Every plant gets its own sensor profile, needs and AI-assisted care plan.')+`<div class="grid plant-grid">${plants.map(p=>`<div class="card plant-card"><div class="section-head"><div><h2 style="font-size:14px">${p.name}</h2><span>${p.zone}</span></div><span class="health ${p.health==='Attention'?'attention':''}">${p.health}</span></div><div class="big-value">${p.moisture}% <small style="font-size:11px;color:var(--muted);font-weight:500">soil moisture</small></div><div class="meter ${p.health==='Attention'?'low':''}" style="width:100%;height:9px"><i style="width:${p.moisture}%"></i></div><div class="plant-metrics"><div class="mini"><small>Temp</small><strong>${p.temp}°C</strong></div><div class="mini"><small>Light</small><strong>${p.light} lx</strong></div><div class="mini"><small>Water target</small><strong>${p.need}%</strong></div></div><div class="profile-note">✦ <strong>AI care note</strong><br>${p.note}</div><button class="btn ${p.health==='Attention'?'btn-primary':'btn-soft'} inspect" data-id="${p.id}">${p.health==='Attention'?'Water now':'View profile'}</button></div>`).join('')}</div>`}
function analyticsView(){return header('Sensor network','Sensor data','Live telemetry from moisture and photosensitive-resistor light sensors.')+`<div class="grid analytics-grid"><div class="card section analytics-wide"><div class="section-head"><h2>Soil moisture</h2><span>Live · last 7 days</span></div>${lineChart([67,63,59,54,48,40,42])}</div><div class="card section"><div class="section-head"><h2>Light levels</h2><span>lux</span></div>${lineChart([45,62,80,71,88,73,78])}</div><div class="card section"><div class="section-head"><h2>Temperature</h2><span>°C</span></div>${lineChart([50,54,58,56,63,61,59])}</div><div class="card section"><div class="section-head"><h2>System telemetry</h2><span>3 / 3 online</span></div><div class="setting"><div><h3>Node 01 · Moisture</h3><p>Last reading 12 sec ago</p></div><span class="health">Online</span></div><div class="setting"><div><h3>Node 02 · Moisture</h3><p>Last reading 8 sec ago</p></div><span class="health">Online</span></div><div class="setting"><div><h3>Node 03 · Light</h3><p>Last reading 5 sec ago</p></div><span class="health">Online</span></div></div></div>`}
function settingsView(){return header('Control centre','Settings','Make Xylem fit the way you grow.')+`<div class="card section"><div class="setting"><div><h3>Dark mode</h3><p>Switch between light and dark layouts.</p></div><button class="toggle" id="themeToggle"><i></i></button></div><div class="setting"><div><h3>Simple layout</h3><p>Keep only the most important farm signals visible.</p></div><button class="toggle on"><i></i></button></div><div class="setting"><div><h3>AI care reminders</h3><p>Gemini-powered recommendations based on your sensor data.</p></div><button class="toggle on"><i></i></button></div><div class="setting"><div><h3>Cloud backup</h3><p>Google Firestore · ready for connection in the full build.</p></div><span class="health">Configured</span></div><div class="setting"><div><h3>Gemini API key</h3><p>Stored locally for this prototype — never displayed in the dashboard.</p></div><button class="btn btn-ghost" id="apiKey">Set API key</button></div></div>`}
function render(view=activePage){const page=qs('#page-'+view);if(view==='dashboard')page.innerHTML=dashboard();if(view==='plants')page.innerHTML=plantsView();if(view==='analytics')page.innerHTML=analyticsView();if(view==='settings')page.innerHTML=settingsView();bind(view)}
function bind(view){qsa('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.view));qsa('.inspect').forEach(b=>b.onclick=()=>openPlant(+b.dataset.id));qsa('.task').forEach(t=>t.onclick=()=>{t.classList.toggle('done');t.querySelector('.check').textContent=t.classList.contains('done')?'✓':'';toast(t.classList.contains('done')?'Task completed':'Task reopened')});if(qs('#waterAlert'))qs('#waterAlert').onclick=()=>water(2);if(qs('#themeToggle'))qs('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');qs('#themeToggle').classList.toggle('on');toast('Theme updated')};if(qs('#apiKey'))qs('#apiKey').onclick=()=>{const key=prompt('Gemini API key (stored only in this browser):');if(key)localStorage.setItem('xylem-gemini-key',key);toast('Gemini key saved locally')};}
function water(id){const p=plants.find(x=>x.id===id);if(!p)return;p.moisture=Math.min(70,p.moisture+24);p.health='Healthy';toast(`${p.name} watered · moisture now ${p.moisture}%`);render('dashboard')}
function openPlant(id){const p=plants.find(x=>x.id===id);qs('#plantModalBody').innerHTML=`<div class="eyebrow">Plant profile · ${p.zone}</div><h2>${p.name}</h2><p class="modal-sub">Individual care profile powered by live sensor readings.</p><div class="modal-stats"><div class="modal-stat"><small>SOIL MOISTURE</small><strong>${p.moisture}%</strong></div><div class="modal-stat"><small>TEMPERATURE</small><strong>${p.temp}°C</strong></div><div class="modal-stat"><small>LIGHT</small><strong>${p.light} lx</strong></div></div><div class="ai-card"><div class="ai-label">✦ AI care recommendation</div><h2>${p.health==='Attention'?'Water this plant now.':'Conditions look good.'}</h2><p>${p.note} Xylem combines sensor history, plant needs and weather forecasts to suggest the next action.</p></div><button class="btn btn-primary" style="margin-top:16px" onclick="document.querySelector('#plantModal').style.display='none'">Done</button>`;qs('#plantModal').style.display='flex'}
qs('#btnCloseModal').onclick=()=>qs('#plantModal').style.display='none';qs('#plantModal').onclick=e=>{if(e.target.id==='plantModal')e.currentTarget.style.display='none'};qs('#btnSignout').onclick=()=>toast('Demo mode — sign out is disabled');
render('dashboard');
setInterval(()=>{plants.forEach(p=>{p.moisture=Math.max(20,Math.min(78,p.moisture+(Math.random()>.55?1:-1)));p.light=Math.max(500,Math.min(1100,p.light+Math.round((Math.random()-.5)*30)))});if(activePage==='dashboard')render('dashboard')},5000);
